# Rewriting the 'calculate_distance' function

Rewrite calculate_distance to use NumPy arrays.

In [2]:
import math

def calculate_distance(coord1, coord2, box_length=None):
    """
    Calculate the distance between two 3D coordinates.
    Parameters
    ----------
    coord1, coord2: list
        The atomic coordinates
    box_length : float
        The box length. If given, the minimum image convention will be used to calculate the distance.

    Returns
    -------
    distance: float
        The distance between the two points.
    """
    distance = 0

    for i in range(3):
        dim_dist = (coord1[i] - coord2[i])
        if box_length:
            dim_dist = dim_dist - box_length * round(dim_dist / box_length)
        dim_dist = dim_dist**2
        distance += dim_dist
    distance = math.sqrt(distance)
    return distance

In [3]:
import numpy as np

point1 = np.array([0, 0, 0])
point2 = np.array([0, 8, 0])

In [4]:
calculate_distance(point1, point2)

8.0

In [5]:
dimensional_distance = point1 - point2
print(dimensional_distance)

[ 0 -8  0]


In [6]:
dd2 = dimensional_distance ** 2
dd2_sum = dd2.sum()
distance = math.sqrt(dd2_sum)

In [7]:
print(distance)

8.0


In [14]:
def calculate_distance_np(coord1, coord2, box_length=None):
    dim_dist = coord2 - coord1

    if box_length:
        dim_dist = dim_dist - box_length * np.round(dim_dist / box_length)
    
    if dim_dist.ndim < 2:
        dim_dist = dim_dist.reshape(1, -1)

    dim_dist_sq = dim_dist ** 2
    dim_dist_sum = dim_dist_sq.sum(axis=1)
    distance = np.sqrt(dim_dist_sum)

    return distance

In [9]:
calculate_distance_np(point1, point2, box_length=10)

array([2.])

In [21]:
point2 = np.array([0, 8, 0])

coord_set1 = np.array([[0, 0, 0], [0, 1, 0]])
coord_set2 = np.array([[0, 8, 0], [0, 1.5, 0]])

print(len(coord_set2))

print(len(coord_set2))

print(len(coord_set2))

calculate_distance_np(coord_set1, coord_set2, box_length=10)
# Exercise - Why am I getting one value here instead of 2? What can I change about my function so that I get two values?

2
2
2


array([2. , 0.5])

In [18]:
calculate_distance_np(point2, coord_set1, 10)

array([2., 3.])

In [12]:
point1.reshape(1, -1) # Adds 1 row, with as many columns as the other points have?

array([[0, 0, 0]])