# Introduction to NumPy Arrays

In [52]:
import math

coordinates = [[0, 0, 0], [0, 0, math.pow(2, 1/6)], [0, 0, 2 * math.pow(2, 1/6)], [math.pow(2, 1/6), 0, 0]]
print(coordinates)

[[0, 0, 0], [0, 0, 1.122462048309373], [0, 0, 2.244924096618746], [1.122462048309373, 0, 0]]


In [53]:
second_coordinate = coordinates[1]
print(coordinates[1])

translation_vector = [0.1, -0.1, 0]

new_coordinate = []
for i in range(len(second_coordinate)):
    translated_coordinate = second_coordinate[i] + translation_vector[i]
    new_coordinate.append(translated_coordinate)

print(new_coordinate)



[0, 0, 1.122462048309373]
[0.1, -0.1, 1.122462048309373]


In [54]:
# Do the same thing using NumPy arrays
import numpy as np

# Create numpy array from list
second_coordinate_np = np.array(second_coordinate)
print(second_coordinate_np)

[0.         0.         1.12246205]


In [55]:
translation_vector_np = np.array(translation_vector)

In [56]:
new_coordinate_np = second_coordinate_np + translation_vector_np
print(new_coordinate_np)

[ 0.1        -0.1         1.12246205]


In [57]:
second_coordinate + translation_vector

[0, 0, 1.122462048309373, 0.1, -0.1, 0]

In [58]:
second_coordinate_np * translation_vector_np

array([ 0., -0.,  0.])

In [59]:
my_array = np.array([0.2, 0.3])
second_coordinate_np + my_array # error - array shapes are not compatible

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
second_coordinate_np.shape

(3,)

In [ ]:
second_coordinate_np.ndim

1

In [ ]:
coordinates

[[0, 0, 0],
 [0, 0, 1.122462048309373],
 [0, 0, 2.244924096618746],
 [1.122462048309373, 0, 0]]

In [ ]:
# Making an array from a nested list creates a 2 dimension numpy array
coordinates_np = np.array(coordinates)

In [ ]:
coordinates_np.shape

(4, 3)

In [ ]:
# Accessing elements of a list
coordinates[1][2]

1.122462048309373

In [ ]:
# Accessing elements in a numpy array
coordinates_np[1, 2]

np.float64(1.122462048309373)

In [ ]:
coordinates

[[0, 0, 0],
 [0, 0, 1.122462048309373],
 [0, 0, 2.244924096618746],
 [1.122462048309373, 0, 0]]

In [ ]:
# Access the 3rd element in every array in this array of arrays
coordinates_np[:, 2]

array([0.        , 1.12246205, 2.2449241 , 0.        ])

## Broadcasting

In [ ]:
coordinates_np.shape

(4, 3)

In [ ]:
translation_vector_np.shape

(3,)

In [ ]:
# Situation: We want to translate all of the atoms using a translation vector.
# Here is how we would do it using lists and the Python Standard Library

num_atoms = len(coordinates)
new_coordinates = []

for n in range(num_atoms):

    atom_coord = coordinates[n]
    updated_coord = []
    for i in range(3):
        translated_coordinate = atom_coord[i] + translation_vector[i]
        updated_coord.append(translated_coordinate)
    
    new_coordinates.append(updated_coord)

print(new_coordinates)

[[0.1, -0.1, 0], [0.1, -0.1, 1.122462048309373], [0.1, -0.1, 2.244924096618746], [1.222462048309373, -0.1, 0]]


In [ ]:
new_coordinates_np = coordinates_np + translation_vector_np
print(new_coordinates_np)

[[ 0.1        -0.1         0.        ]
 [ 0.1        -0.1         1.12246205]
 [ 0.1        -0.1         2.2449241 ]
 [ 1.22246205 -0.1         0.        ]]


In [ ]:
coordinates_np > 0.0

array([[False, False, False],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False]])

In [ ]:
greater_than_zero_values = coordinates_np[coordinates_np > 0.0]
print(greater_than_zero_values)

[1.12246205 2.2449241  1.12246205]


## Array Axes

In [60]:
coordinates_np.ndim

2

In [64]:
coordinates_np.shape

# 4 Rows, 3 Columns. Basically means 4 sets of coordinates with 3 dimensions

(4, 3)

In [66]:
# Geometrical examples - center of mass
print(coordinates_np.mean())

print(coordinates_np.mean(axis=0))
print(coordinates_np.mean(axis=1))

0.3741540161031243
[0.28061551 0.         0.84184654]
[0.         0.37415402 0.74830803 0.37415402]
